title: MediConnect     # your site’s display title
theme: jekyll-theme-minimal             # or the theme you selected
# navigation links (optional):
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
